### ISSUE TITLE
Add sparql converters

### ISSUE THREAD

**Issue by jnehring** [dkt-projekt/DktBrokerStandalone#10]
We suggested to the partners to use the sparql converters but they are not included in the current installation. Please include it in the broker. You can copy the configuration from FREME broker: [pom.xml](https://github.com/freme-project/freme-packages/blob/master/broker-dev/pom.xml#L37-40) and [package.xml](https://github.com/freme-project/freme-packages/blob/master/broker-dev/src/main/resources/package.xml#L19)

**Comment by PeterBourgonje** [comment]
Fixed. (https://github.com/dkt-projekt/DktBrokerStandalone/commit/5f646b7326c1a503adbb06bd74661cd70b4ca045)

**Comment by jnehring** [comment]
I wanted to test but the dev server seems down. Could you test it?

I reopen the ticket to remind us to test if it really works.

**Comment by jnehring** [comment]
Sorry I used the old dev server. On the new server the API is up and running.

**Comment by PeterBourgonje** [comment]
Ok, great. So we can close this now?
