### ISSUE TITLE
Dkt Docker Container

### ISSUE THREAD

**Issue by sraeuchle** [dkt-projekt/DktBrokerStandalone#8]
Is it possible to split the DKT Services into a few jars to run them independent? In this case I would like to put each Service into a Docker Container and combine them in a Docker-Compose File.

**Comment by jnehring** [comment]
Yes this is possible. I suggest this documentation: https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/gettingStarted_SysAdmins.html

Basically you can take the current DktBrokerStandalone and remove the parts you do not need from the package.xml file. You can also remove the services you dont need from pom.xml so the package becomes smaller.

**Comment by sraeuchle** [comment]
Ok, if i do it that way, i get one big Docker Image with all Services inside. Is that the case all partners wanna have?

What I'm trying to do is split the Services in multiple Docker Images. Let's say one Docker Image for e-NLP and another for e-Clustering ...etc. In this case, i can use the Services I need, without touching your Code or pom.xml. And I can scale up the Services as needed in a Cloud Environment. 

If I understand the Documentation correcty i need to build a pure e-NLP Service, e-Clustering etc. myself and connect it to the Common used MySQL Freme Database. Is that correct? How can i build and adjust your proxy Service in this case?

**Comment by jnehring** [comment]
We agreed that no more effort will be put in creating docker containers. The partners can use the public APIs.
